### ISSUE TITLE
AttributeError: 'PostGIS' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by reinvantveer** [geopython/stetl#121]
**Describe the bug**
Hi. We're using the Docker image version 1.5.2 at https://hub.docker.com/r/nlextract/nlextract to load the BAG2 into our database on Kubernetes infrastructure. However, we're running into an error when creating the views: `AttributeError: 'PostGIS' object has no attribute 'cursor'`.

**To Reproduce**
The container commands executed are as follows:
```
# Filename for zip file on download page with mmyyyy
export zipfile=BAGNLDL-08$(date '+%m%Y').zip
export url=https://extracten.bag.kadaster.nl/lvbag/extracten/Nederland%20LVC/${zipfile}
echo Downloading from ${url}...
curl -fsSL ${url} -o ${zipfile} || exit 1

# The db config for Docker contexts (local dev etcetera)
cat << EOF > /nlx/bagv2/etl/options/docker.args
pg_host=${PGHOST}
pg_port=${PGPORT}
pg_user=${PGUSER}
password=${PGPASSWORD}
pg_db=geodb
schema=bag
bag_file_ext=zip
EOF

# Copy to the default args for k8s contexts
cp /nlx/bagv2/etl/options/docker.args /nlx/bagv2/etl/options/default.args

# Execute the import procedure
bagv2/etl/etl.sh -a bag_input_file=$(pwd)/${zipfile}
```
**Expected Behavior**
A process running to completion

**Screenshots or Logfiles**
If applicable, add screenshots or logfile texts, to help explain your problem.

```

INSERT INTO nlx_bag_log (actie, bestand) VALUES ('views aangemaakt', 'create-views.sql');
--
with parms: None
2021-06-14 19:11:55,088 component INFO StringFileInput invokes=3 time(total, min, max, avg) = 0.052 0.012 0.020 0.017
2021-06-14  19:11:55,088 component INFO PostgresDbOutput invokes=3 time(total, min,  max, avg) = 7208.033 414.027 6794.006 2402.678
Traceback (most recent call last):
File "/nlx/externals/stetl/bin/stetl", line 43, in &lt;module&gt;
main()
File "/nlx/externals/stetl/bin/stetl", line 36, in main
etl.run()
File "/nlx/externals/stetl/stetl/etl.py", line 157, in run
chain.run()
File "/nlx/externals/stetl/stetl/chain.py", line 172, in run
packet = self.first_comp.process(packet)
File "/nlx/externals/stetl/stetl/component.py", line 213, in process
packet = self.next.process(packet)
File "/nlx/externals/stetl/stetl/component.py", line 199, in process
packet = self.invoke(packet)
File "/nlx/externals/stetl/stetl/output.py", line 22, in invoke
packet = self.write(packet)
File "/nlx/externals/stetl/stetl/outputs/dboutput.py", line 82, in write
rowcount = db.tx_execute(packet.data)
File "/nlx/externals/stetl/stetl/postgis.py", line 152, in tx_execute
return self.cursor.rowcount

AttributeError: 'PostGIS' object has no attribute 'cursor'
/nlx
--
```

**Context (please complete one or more from the following information):**
 - OS: Docker image nlextract/nlextract:1.5.2
 - Python Version as contained in image
 - Stetl Version as contained in image
 - Stetl Input/Output/Filter Component as in image
 - Stetl Config file as listed above

If running with Docker:
 - Docker installed version
 - Stetl Docker Image version

Our cluster isn't using Docker as container runtime, but containerd.

**Additional context**
I imagine this error can originate at a lost db connection (but I'm not sure) in which case the `PostGIS` object no longer has a `cursor` object. But I could be wrong. In any case, the script should (IMHO) null-check the  `PostGIS` object for a valid cursor attribute before returning it.

**Comment by reinvantveer** [comment]
There may be something here: the `PostGIS` method 
```
    def tx_execute(self, sql, parameters=None):
        self.e = None
        try:
            self.connect()
            self.execute(sql, parameters)
            self.connection.commit()
            self.connection.close()

            # log.debug(self.cursor.statusmessage)
        except Exception as e:
            self.e = e
            log.error("error %s in transaction: %s with parms: %s" % (str(e), str(sql), str(parameters)))

        return self.cursor.rowcount
```
is required to return a self.cursor.rowcount, but it isn't guaranteed to be there, especially in cases where an exception is thrown.

**Comment by reinvantveer** [comment]
I've attached a full log below. BTW there's an awful lot of usernames and passwords being logged in plaintext, this should probably be filed as a separate issue. I made sure to remove them from the logs.

[nlextract-bag2-update-h97mn-346836924_main.log](https://github.com/geopython/stetl/files/6655220/nlextract-bag2-update-h97mn-346836924_main.log)

**Comment by reinvantveer** [comment]
Also I'm going to see what I can do to contribute here

**Comment by justb4** [comment]
Thanks @reinvantveer , hard to analyse. We've run Stetl before in K8s. Strange thing is that the main ETL steps execute ok. It is in the last "Post" SQL step: `input_sql_post|output_postgres_sql` for `fill-rel-tables.sql` that the error occurs. 
So all parameters are correct.

There may be a (PG) memory issue for example, popping up as a connection error. 
I've also seen that running SQL scripts via Python `psycopg2` sometimes creates issues which did not pop-up when using straight `psql`.

You may also try the `latest` Docker image but I won't expect differences. We had no problems e.g. running that version for BAGv2 June 2021 for geotoko.nl a few days ago. 

But the error handling in Stetl PostGIS `tx_execute()` is indeed not robust.

We have tried to eliminate all password/security related info from Stetl logging e.g. via #79. But apparently some slip through.
Any contribution welcome!
