### ISSUE TITLE
Add Python implementation to support BAGv2 Extract and Mutations

### ISSUE THREAD

**Issue by petersaalbrink** [geopython/stetl#126]
**Is your feature request related to a problem? Please describe.**
I use [NLExtract](https://github.com/nlextract/NLExtract) for processing the BAGv2 Extract. I'd like to use NLExtract to process BAG Mutations as well. But NLExtract has a dependency on Stetl, and the GDAL BAG-LV driver (which is included with Stetl) does not support processing BAG Mutations. 

**Describe the solution you'd like**
A Python implementation as alternative to the GDAL BAG-LV driver, and an extension of it that supports BAG Mutations.

**Describe alternatives you've considered**
Alternatives include extending the GDAL BAG-LV driver, or processing BAG Mutations without Stetl.

**Additional context**
See https://github.com/nlextract/NLExtract/issues/349

**Comment by justb4** [comment]
This can be useful feature, but belongs to the NLExtract project: https://github.com/nlextract/NLExtract/issues/349. Stetl is a generic ETL library. BAG ETL is domain specific. We can discuss within the NLExtract project.
