### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by sebastic** [geopython/stetl#23]
Currently the Stetl module doesn't appear to support Python 3, building with Python 3 results in SyntaxErrors:

```
  File "/usr/lib/python3.4/dist-packages/stetl/postgis.py", line 34
    except psycopg2.DatabaseError, e:
                                 ^
SyntaxError: invalid syntax

  File "/usr/lib/python3.4/dist-packages/stetl/main.py", line 84
    print name, data
             ^
SyntaxError: Missing parentheses in call to 'print'

  File "/usr/lib/python3.4/dist-packages/stetl/factory.py", line 26
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3.4/dist-packages/stetl/etl.py", line 73
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3.4/dist-packages/stetl/utils/apachelog.py", line 183
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3.4/dist-packages/stetl/inputs/fileinput.py", line 183
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3.4/dist-packages/stetl/inputs/deegreeinput.py", line 158
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3.4/dist-packages/stetl/filters/templatingfilter.py", line 173
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3.4/dist-packages/stetl/filters/xmlassembler.py", line 68
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3.4/dist-packages/stetl/filters/gmlsplitter.py", line 130
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by justb4** [comment]
No, as Python2 is the default on most systems I know of, i.e. there was 
no need for Python3 support. I have no idea how difficult adding support 
is. Think there is some compat lib? ALso requires double testing. Do you 
have an indication how much effort this is?

**Comment by sebastic** [comment]
The [2to3 utility](http://python3porting.com/2to3.html) helps to convert from Python 2 to 3. Only for complex code bases it tends to require separate lib trees for each Python version. Supporting both is generally not very difficult.

Double testing should be easy with Travis. My other PR (#24) should help with testing via pypi.

**Comment by justb4** [comment]
See the discussions under #81 that lead to the Stetl Py2/3 strategy. In short:

* no Stetl versions with both Py2+Py3 support will be released
* v1.3. will be last release to support Py2 (2.7+) (by @justb)
* a `1.3` maintenance branch will be started, but only for urgent/security fixes
* v2.0 will be first release supporting Py3-only (3.4.2+) (all)
* v.2.0 will change `import` conventions: full `stetl.` package imports and relative `.` within packages
* v.2.0 will change  Stetl `.cfg` package `class=` convention: Stetl classes must have full package spec, e.g. `class = stetl.inputs.fileinput.XmlFileInput`
* commits will reference this issue and any PRs for Py3 support
* @borrob 's [branch](https://github.com/borrob/stetl/tree/python3) will be used to integrate Py3-only changes for Stetl v2.0. and integrate via #81 or a new PR.

**Comment by justb4** [comment]
@sebastic @fsteggink @borrob : I've added a Project: https://github.com/geopython/stetl/projects/1 to gather the various discussions, issues, PRs and Todo's around Py3 migration. Maybe this is too fine-grained and cards should be issues (?) but alas for history. We are quite far, into the famous last 10%...

**Comment by justb4** [comment]
We're all done, Stetl v2 supporting Py3-only available on PyPi and DockerHub, now into maintenance mode, closing, thanks all @sebastic @borrob !
