### ISSUE TITLE
Provide compact and reusable Dockerfile

### ISSUE THREAD

**Issue by justb4** [geopython/stetl#61]
The current Dockerfile for Stetl needs several  improvements:

1.  its Docker Image is "bulky", about 1.4GB, due to use of Ubuntu as base Image
2. hard to reuse: single ENTRYPOINT, harder to add e.g. user-plugins
3. not in basedir of git-repo, harder to automate in e.g. Docker Hub/Cloud
4. provide Docker Compose example(s)

Ad 1) better is to use a small-sized Python base image like [python-alpine Linux](https://hub.docker.com/_/python/).

**Comment by justb4** [comment]
Hit the following problem when testing: 
http://bugs.alpinelinux.org/issues/8080
GDAL 2.1.3 from Alpine does not support GML reading via libexpat (nor Xerces).

**Comment by justb4** [comment]
@sebastic maybe you have an idea for building a small-size Stetl Docker Image with GDAL2?

* tried Alpine Linux but GDAL2 is build with few drivers (see above and [my bug report](http://bugs.alpinelinux.org/issues/8080)). Gave up: See [Alpine Docker file](https://github.com/geopython/stetl/blob/master/docker/Dockerfile.alpine)
* now trying Debian Stretch Slim now: GDAL Stretch is v2.1.2 but there is no 2.1.2 in PyPi for Python bindings (only 2.1.0 or 2.1.3 in 2.1.* range) so `pip install GDAL` fails.
See [Debian Stretch Docker file](https://github.com/geopython/stetl/blob/master/Dockerfile). 

Alpine Docker images with Stetl are about 500MB, Debian around 1GB, Ubuntu about 1.6GB, hence is attractive to use Alpine. But if we get GDAL2 working I'll be happy to go with Debian for coming time.

**Comment by sebastic** [comment]
For the Debian stretch image you can install the Python bindings with:
```
apt-get install python3-gdal python-gdal
```

**Comment by justb4** [comment]
@sebastic tried that but failed, also for others like `lxml`. E.g. `from gdal import ogr` failed. Pff, now I see why: Stretch Python Docker installs its own Python under `/usr/local` next to system Python onder `/usr/lib`. Python packages via `apt` are under `/usr/lib` and via `pip` under `/usr/local`,  e.g. bash-ing into Docker Container:

```
root@3290f374f9c6:~# which python
/usr/local/bin/python
root@3290f374f9c6:~# /usr/bin/python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@3290f374f9c6:~# python
Python 2.7.14 (default, Oct 23 2017, 20:39:24) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@3290f374f9c6:~# ls /usr/local/lib/python2.7/site-packages/
Jinja2-2.9.6.dist-info	  easy-install.pth	    jinja2		  mock			 pbr		      pkg_resources		  setuptools-36.6.0.dist-info  wheel
MarkupSafe-1.0.dist-info  easy_install.py	    lxml		  mock-2.0.0.dist-info	 pbr-3.1.1.dist-info  psycopg2			  six-1.11.0.dist-info	       wheel-0.30.0.dist-info
README			  funcsigs		    lxml-4.1.0.dist-info  nose2			 pip		      psycopg2-2.7.3.2.dist-info  six.py
Stetl-1.1.0rc5-py2.7.egg  funcsigs-1.0.2.dist-info  markupsafe		  nose2-0.6.5.dist-info  pip-9.0.1.dist-info  setuptools		  six.pyc

root@3290f374f9c6:~# ls /usr/lib/python2.7/dist-packages/
GDAL-2.1.2.egg-info	       chardet		       gdal.pyc        gdalnumeric.pyc		      lxml-3.7.1.egg-info    ogr.pyc  pkg_resources	   webencodings
README			       chardet-2.3.0.egg-info  gdalconst.py    html5lib			      numpy		     osgeo    six-1.10.0.egg-info  webencodings-0.5.egg-info
beautifulsoup4-4.5.3.egg-info  debconf.py	       gdalconst.pyc   html5lib-0.999999999.egg-info  numpy-1.12.1.egg-info  osr.py   six.py
bs4			       gdal.py		       gdalnumeric.py  lxml			      ogr.py		     osr.pyc  six.pyc

```
Also extending `PYTHONPATH` doesn't help...This explains a lot of issues I had in other projects with Python Docker images with GDAL Python bindings (always needed both the `apt` and `pip` version, while the `apt` version was never used). Will try a bare `Stretch` and use just system Python...

Possibly interesting for @fsteggink and PDOK (who still compile GDAL2 on Jessie) as well...Looks were getting there...

**Comment by justb4** [comment]
Ok, thanks @sebastic and @fsteggink (for suggesting Debian): the new [Dockerfile](https://github.com/geopython/stetl/blob/master/Dockerfile) is based on `stretch-slim` (55MB), builds within one minute, Stetl tests ok, and is just 360MB (previous Ubuntu 16.04 Stetl Image was 1.6GB...)!

**Comment by justb4** [comment]
Ready for now, into maintenance mode.
