### ISSUE TITLE
Inconsistent use of nose

### ISSUE THREAD

**Issue by sebastic** [geopython/stetl#89]
`requirements-dev.txt` uses [`nose2`](https://pypi.org/project/nose2/), but `setup.py` uses [`nose`](https://pypi.org/project/nose/).

If `nose2` should be used, `setup.py` should use `nose2` as well.

**Comment by justb4** [comment]
yes, it should all  be `nose2`.

**Comment by justb4** [comment]
Should be fixed, closing, pls re-open if changed required.

**Comment by sebastic** [comment]
The `nosetests` configuration in `setup.cfg` made `python3 setup.py test` work with `nose`, this doesn't work with `nose2`.
