### ISSUE TITLE
Travis configuration still uses Python 2

### ISSUE THREAD

**Issue by sebastic** [geopython/stetl#92]
The Travis configuration still uses Python 2:
```
  - sudo apt-get install -qq build-essential python-dev python-setuptools
  - sudo apt-get install -qq python-lxml libgdal-dev python-psycopg2 python-jinja2 gdal-bin
```
```
  # follow GDAL installed version for Python bindings
  - pip install GDAL==`gdalinfo --version | cut -d' ' -f2 | cut -d',' -f1`
  # - pip install -r requirements-main.txt
  - python setup.py install
  - pip install -r requirements-dev.txt
```
For Python 3 this should be:
```
  - sudo apt-get install -qq build-essential python3-dev python3-setuptools
  - sudo apt-get install -qq python3-lxml libgdal-dev python3-psycopg2 python3-jinja2 gdal-bin
```
```
  # follow GDAL installed version for Python bindings
  - pip3 install GDAL==`gdalinfo --version | cut -d' ' -f2 | cut -d',' -f1`
  # - pip3 install -r requirements-main.txt
  - python3 setup.py install
  - pip3 install -r requirements-dev.txt
```
But it seems that the python packages aren't actually used. If the packages are preferred over the modules installed via pip, then the package names need to be changed per the above, otherwise the python packages shouldn't be installed at all.

**Comment by justb4** [comment]
Ok, makes sense, but I think/hope the Travis build is still using Py3. Are you already PR-ing? Otherwise I can make this change. The [Dockerfile](https://github.com/geopython/stetl/blob/master/Dockerfile#L59) and documentation also has these issues.

**Comment by sebastic** [comment]
I don't have a PR in the works, as Travis doesn't work in my browser.

**Comment by justb4** [comment]
Ok, will make the changes.

**Comment by justb4** [comment]
Updated Travis and Dockerfile to explicitly use python3: pip3, packages, command. Closing, pls re-open if still changes needed.

**Comment by sebastic** [comment]
The Dockerfiles still uses pip on line 56:
```
	pip install ${PYTHON_EXTRA_PIP_PACKAGES} ;\
```
