### ISSUE TITLE
include newer GDAL

### ISSUE THREAD

**Issue by stvno** [geopython/stetl#93]
GDAL 2.1 doesn't support postgresql 12, so you cannot export to a postgres 12 database

**Comment by justb4** [comment]
One thing we could do is upgrade the Docker file from `buster-slim` (Debian 10) to `bullseye-slim` (debian 11) although `bullseye` is the current `Debian testing` release as Debian 11 support GDAL (3.0.4) currently: https://packages.debian.org/testing/science/gdal-bin .Thoughts? See also geopython/pygeoapi#359

**Comment by justb4** [comment]
Hmm but `Debian buster` supports GDAL 2.4.0, maybe that is a better first step: https://packages.debian.org/buster/science/gdal-bin

**Comment by fsteggink** [comment]
For what's worth, I've used GDAL version 2.4.4 for a couple of months now with Stetl, without any issues. This was not on a recent version of Stetl though, but I'm not expecting any problems. I've built GDAL myself. Using your own GDAL build could be a good solution for the Docker container, but perhaps not on a bare machine without any build tools.

**Comment by justb4** [comment]
I propose to follow the same conventions as the [pygeoapi Dockerfile](https://github.com/geopython/pygeoapi/blob/master/Dockerfile), based on Bullseye-slim (Debian 11) with GDAL v3 without any compiles.
