### ISSUE TITLE
WFS check is failing

### ISSUE THREAD

**Issue by fsteggink** [geopython/stetl#97]
When checking out the Travis logs from the PR's I've recently done, I've noticed that the WFS check is failing, although the build itself has succeeded. This log can be found [here](https://travis-ci.org/github/geopython/stetl/jobs/709916872).
This can simply be fixed by updating the WFS endpoint in examples/basics/8_wfs/etl.cfg.
More information can be found [here](https://www.pdok.nl/-/bag-wms-en-wfs-versie-1.0-wordt-per-1-juli-uit-gefaseerd.).

**Comment by justb4** [comment]
Thanks. Yes, clear, the Nth update for this URL-change needed....
