### ISSUE TITLE
Version support and upgrades: Python, lxml, GDAL, Debian in Dockerfile

### ISSUE THREAD

**Issue by justb4** [geopython/stetl#99]
Some version upgrades are required:

* Python: drop 3.4 and 3.5 support to at least fix Travis build, still 3.6 needed? add 3.8
* `lxml` think for e.g. NLExtract (`SubFeatureHandler`) support need at least > 4.4.2 
* GDAL: support GDAL >= 3?

At least for the Dockerfile I would like to aim for using Debian bullseye-slim (supports Python 3.8 and GDAL 3.1.2).

See also #93 and recent PRs #96 #95 #94.

**Comment by fsteggink** [comment]
Regarding lxml, I've used 4.4.2 for quite a while now, because of the NLExtract SubFeatureHandler. So far I've not experienced any issues.
